"""rename and replace fields names for site and provider

Revision ID: 13fc4f3850c2
Revises: 6d012c5cb6f3
Create Date: 2025-11-24 11:32:28.200250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fc4f3850c2'
down_revision = '6d012c5cb6f3'
branch_labels = None
depends_on = None


def upgrade():
    pre_upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('mobile_network_code', sa.String(length=10), nullable=False))
    op.drop_constraint(op.f('provider_mnc_key'), 'provider', type_='unique')
    op.create_unique_constraint(None, 'provider', ['mobile_network_code'])
    op.drop_column('provider', 'mnc')
    op.add_column('site', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('site', sa.Column('latitude', sa.Float(), nullable=False))
    op.drop_column('site', 'y_l93')
    op.drop_column('site', 'x_l93')
    # ### end Alembic commands ###
    post_upgrade()


def downgrade():
    pre_downgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('x_l93', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('site', sa.Column('y_l93', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('site', 'latitude')
    op.drop_column('site', 'longitude')
    op.add_column('provider', sa.Column('mnc', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'provider', type_='unique')
    op.create_unique_constraint(op.f('provider_mnc_key'), 'provider', ['mnc'], postgresql_nulls_not_distinct=False)
    op.drop_column('provider', 'mobile_network_code')
    # ### end Alembic commands ###


    post_downgrade()


def pre_upgrade():
    pass


def post_upgrade():

    pass


def pre_downgrade():
    pass


def post_downgrade():
    pass