"""init provider and site models

Revision ID: 6d012c5cb6f3
Revises: 
Create Date: 2025-11-23 15:26:14.020367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d012c5cb6f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pre_upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('mnc', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mnc'),
    sa.UniqueConstraint('name')
    )
    op.create_table('site',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('x_l93', sa.Float(), nullable=False),
    sa.Column('y_l93', sa.Float(), nullable=False),
    sa.Column('has_2g', sa.Boolean(), nullable=False),
    sa.Column('has_3g', sa.Boolean(), nullable=False),
    sa.Column('has_4g', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    post_upgrade()


def downgrade():
    pre_downgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site')
    op.drop_table('provider')
    # ### end Alembic commands ###


    post_downgrade()


def pre_upgrade():
    pass


def post_upgrade():

    pass


def pre_downgrade():
    pass


def post_downgrade():
    pass